# Data Preprocessing Tools

## Importing the libraries

In [1]:
# Import the necessary libraries for data manipulation, analysis, and visualization.

# NumPy is a library for numerical operations and array handling.
import numpy as np

# Pandas is a powerful library for data manipulation and analysis, providing data structures like DataFrames.
import pandas as pd

# Matplotlib is a popular library for creating static, animated, or interactive visualizations in Python.
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
# Load a dataset from a CSV (Comma-Separated Values) file into a Pandas DataFrame.
# The dataset is expected to be stored in a file named "Data.csv."
dataset = pd.read_csv("Data.csv")

# Extract the feature variables 'x' from the DataFrame.
# It selects all rows and the first three columns (0, 1, and 2) as features.
x = dataset.iloc[:, :3].values

# Extract the target variable 'y' from the DataFrame.
# It selects the "Purchased" column as the target variable.
y = dataset["Purchased"].values

In [3]:
# Display the first few rows of the loaded dataset for a quick overview.
print(dataset.head())

# Display the feature variables 'x' extracted from the dataset.
print(x)

# Display the target variable 'y' extracted from the dataset.
print(y)

# Display the number of dimensions of the 'x' array.
print(x.ndim)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
2


In [4]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## Taking care of missing data

In [5]:
# This code snippet is using scikit-learn's SimpleImputer to handle missing data in a dataset.

# Import the SimpleImputer class from the sklearn.impute module.
from sklearn.impute import SimpleImputer

# Create an instance of the SimpleImputer class with the following settings:
# - missing_values: Replace NaN (Not a Number) values with the mean of the column.
# - strategy: The imputation strategy is set to 'mean'.
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit the imputer to a specific subset of the dataset 'x'. It focuses on columns 1 and 2 (0-based index).
# This step calculates the mean of each column and stores it for later imputation.
imputer.fit(x[:, 1:3])

# Transform the same subset of the 'x' dataset using the fitted imputer.
# NaN values in columns 1 and 2 will be replaced with the corresponding means.
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding categorical data

### Encoding the Independent Variable

In [7]:
# Import the necessary libraries for column transformation and one-hot encoding.
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Create a ColumnTransformer instance, 'ct,' to apply specific transformations to different columns.
# In this case, it's configured to apply the 'OneHotEncoder' transformation to column 0 (categorical data),
# while leaving the remaining columns unchanged ('passthrough').

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)

# Transform the input data 'x' using the configured column transformations.
# The 'fit_transform' method applies one-hot encoding to the specified column (column 0) and keeps the rest unchanged.
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [9]:
# Import the necessary library for label encoding.
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance, 'le,' for transforming categorical labels into numerical values.
le = LabelEncoder()

# Fit and transform the target variable 'y' using the LabelEncoder.
# This process assigns a unique numerical code to each distinct category in 'y.'
y = le.fit_transform(y)


In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
# Import train_test_split for data splitting.
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Define the testing set size (20%) and ensure reproducibility with a seed (random_state=1).

In [12]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]


## Feature Scaling

In [16]:
# Import the StandardScaler class from scikit-learn, which is used for feature scaling.
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance, 'sc,' to scale the features.
sc = StandardScaler()

# Apply feature scaling to the training set.
# - Select columns from the 4th column (0-based index) onwards and standardize their values.
# - Feature scaling ensures that the features have a mean of 0 and a standard deviation of 1.
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

# Apply the same feature scaling to the testing set.
# - It's important to use the same scaling parameters (mean and standard deviation) as the training set to maintain consistency.
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
